# Generated by Django 5.0.3 on 2025-05-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferenciausuario',
            old_name='equipo_favorito',
            new_name='equipo',
        ),
    ]
