# Generated by Django 5.0.3 on 2025-05-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_rename_equipo_favorito_preferenciausuario_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferenciausuario',
            old_name='equipo',
            new_name='equipo_favorito',
        ),
    ]
