# Generated by Django 5.0.3 on 2025-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0006_rename_equipo_preferenciausuario_equipo_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciausuario',
            name='logo_equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
